import 'react'
import 'mobx'
import 'mobx-react'
import 'router5'
import 'router5/plugins/logger'
import 'router5/plugins/listeners'
import 'router5/plugins/browser'
import 'react-router5'

import 'prismjs'
import 'prismjs/components/prism-ruby'
import 'prismjs/components/prism-bash'
import 'prismjs/components/prism-docker'
import 'prismjs/components/prism-sass'
import 'prismjs/components/prism-jsx'
import 'prismjs/components/prism-yaml'
import 'prismjs/components/prism-json'
import 'prismjs/components/prism-elixir'
import 'prismjs/components/prism-coffeescript'

import 'animate.css/animate.css'
import 'purecss/build/pure.css'
import 'purecss/build/grids-responsive.css'
import 'styles/global/overrides.css'

import 'vendor/@google/styles/material-icons.css'
import 'vendor/@prismjs/styles/dracula.css'
